language: go

os:
  - linux
  # - osx

matrix:
  allow_failures:
    - os: osx
    - go: 1.10beta1

go:
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - 1.9.x
  - 1.10beta1

before_install:
  - go get github.com/wadey/gocovmerge
  - go get -v ./...

script:
  - make test
  - make cover
  - cp build/report.out coverage.txt
  - make clean

after_success:
  - bash <(curl -s https://codecov.io/bash)