language: go

os:
  - linux
  # - osx

matrix:
  allow_failures:
    - os: osx
    - go: 1.10beta1
    - go: tip

go:
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - "1.10"
  - tip
  - 1.10beta1

before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/wadey/gocovmerge
  - go get -v ./...

script:
  - make testall
  - cp build/report.out coverage.txt

after_success:
  - $GOPATH/bin/goveralls -coverprofile=build/report.out -service=travis-ci
  - bash <(curl -s https://codecov.io/bash)
  - make clean