language: go

go:
  - 1.7
  - 1.8
  - 1.9

before_install:
  - go get -v ./...

script:
  - ./compile-coverage
  - cp build/report.out coverage.txt

after_success:
  - bash <(curl -s https://codecov.io/bash)