language: go

go:
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - 1.9.x

before_install:
  - go get github.com/wadey/gocovmerge
  - go get -v ./...

script:
  - make test
  - make cover
  - cp build/report.out coverage.txt
  - make clean

after_success:
  - bash <(curl -s https://codecov.io/bash)