language: go

go:
  - 1.8
  - 1.9
  - 1.9.x

before_install:
  - go get github.com/wadey/gocovmerge
  - go get -v ./...

script:
  - make cover
  - cp build/report.out coverage.txt

after_success:
  - bash <(curl -s https://codecov.io/bash)